package graph;

/**
 * Kept running into array-out-of-bounds issues when getting more vertices than expected, so a little accessor here
 * to ensure that colours can always be assigned, even if duplicates!
 */
public class Colours {
    static String[] colours = {
            "red",
            "green",
            "lightblue",
            "magenta",
            "cyan",
            "yellow",
            "orange",
            "slategrey",
            "blue",
            "lightred",
            "brown",
            "darkgoldenrod",
            "crimson",
            "blanchedalmond",
            "blueviolet",
            "darkorange",
            "darkorchid",
            "dodgerblue",
            "chartreuse",
            "darkolivegreen",
            "moccasin",
            "maroon1",
            "lightyellow3",
            "yellowgreen",
            "sandybrown",
            "aquamarine",
            "brown1",
            "brown2",
            "brown3",
            "brown4",
            "cadetblue",
            "cadetblue1",
            "cadetblue2",
            "cadetblue3",
            "cadetblue4",
            "chocolate",
            "chocolate1",
            "chocolate2",
            "chocolate3",
            "chocolate4",
            "coral",
            "coral1",
            "coral2",
            "coral3",
            "coral4",
            "burlywood",
            "burlywood1",
            "burlywood2",
            "burlywood3",
            "burlywood4",
            "darkorchid1",
            "darkorchid2",
            "darkorchid3",
            "darkorchid4",
            "deeppink",
            "deeppink1",
            "deeppink2",
            "deeppink3",
            "deeppink4",
            "deepskyblue",
            "deepskyblue1",
            "deepskyblue2",
            "deepskyblue3",
            "deepskyblue4",
            "gold",
            "gold1",
            "gold2",
            "gold3",
            "gold4",
            "lightsalmon",
            "lightsalmon1",
            "lightsalmon2",
            "lightsalmon3",
            "lightsalmon4",
            "mediumorchid",
            "mediumorchid1",
            "mediumorchid2",
            "mediumorchid3",
            "mediumorchid4",
            "royalblue",
            "royalblue1",
            "royalblue2",
            "royalblue3",
            "royalblue4",
            "seagreen",
            "seagreen1",
            "seagreen2",
            "seagreen3",
            "seagreen4",
            "tan",
            "tan1",
            "tan2",
            "tan3",
            "tan4",
            "tomato",
            "tomato1",
            "tomato2",
            "tomato3",
            "tomato4",
            "wheat",
            "wheat1",
            "wheat2",
            "wheat3",
            "wheat4"
    };

    public static String getColour(int index) {
        if (index >= colours.length) {
            index = index % colours.length;
        }

        return colours[index];

    }

}
